AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance with elastic IP association | @AUTHOR: Raj Tilak Bhowmick | @DATE: 07-09-2021

Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues: [t2.nano, t2.micro, t2.small, t3.nano, t3.small, t3.medium]
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of existing key-pair.
  SSHCidrIp:
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups: [!Ref EC2SecurityGroup]

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access to instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHCidrIp

  EC2ElasticIp:
    Type: AWS::EC2::EIP

  EC2ElasticIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref EC2ElasticIp
